# Workflow for running Tutorials on GitHub Actions
# Work by running converting all .ipynb to .py
# then run all .py in the tutorials folder

name: Run Tutorials
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  RunNotebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        pip install .
        pip install -r tutorials/requirements.txt
    - name: Convert to py
      run: |
        jupyter nbconvert --to python ./tutorials/*.ipynb
    - name: Run notebooks
      # run all python script in tutorials folder
      run: |
        rm ./tutorials/customizing_your_pipeline.py  # ignore this script (requires a GPU)
        for f in tutorials/*.py; do python "$f"; done